#!/usr/bin/env ruby

require 'queue_workers/command_line_options'
require 'queue_workers/compute_report_worker'
require 'queue_workers/run_workers'

options = delayed_cache_worker_options

run_worker_with_cache(ComputeReportWorker, **options)
