#!/usr/bin/env ruby

require 'queue_workers/command_line_options'
require 'queue_workers/planner'
require 'queue_workers/run_workers'

options = cache_worker_options

run_worker_with_cache(Planner, **options)
