#!/usr/bin/env ruby

require 'queue_workers/command_line_options'
require 'queue_workers/send_report_worker'
require 'queue_workers/run_workers'

options = regular_worker_options

run_worker(SendReportWorker, **options)
